### ISSUE TITLE
前几天突然就启动不了了  希望博主看看

### ISSUE THREAD

**Issue by zczczczczczczczczczczc** [13812851221/-rxrw-daily_morning#26]
Collecting xmltodict==0.13.0
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Installing collected packages: optionaldict, xmltodict, urllib3, six, pycparser, idna, charset-normalizer, certifi, requests, python-dateutil, cffi, wechatpy, cryptography
Successfully installed certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.0 cryptography-37.0.4 idna-3.3 optionaldict-0.1.2 pycparser-2.21 python-dateutil-2.8.2 requests-2.28.1 six-1.16.0 urllib3-1.26.11 wechatpy-1.8.18 xmltodict-0.13.0

Notice:  A new release of pip is available: 22.3.1 -> 23.0
Notice:  To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/runner/work/1a1a1a/1a1a1a/./main.py", line [50](https://github.com/zczczczczczczczczczczc/1a1a1a/actions/runs/4169984585/jobs/7218676698#step:4:51), in <module>
    wea, temperature, highest, lowest = get_weather()
                                        ^^^^^^^^^^^^^
  File "/home/runner/work/1a1a1a/1a1a1a/./main.py", line 24, in get_weather
    weather = res['data']['list'][0]
              ~~~^^^^^^^^
KeyError: 'data'
Error: Process completed with exit code 1.

**Comment by liangyude007** [comment]
天气获取失败，具体修复方式参考上一篇Issue

**Comment by zZcCqQ-BBtj** [comment]
> 天气获取失败，具体修改方式参考上一篇Issue
大佬，我fork你的，为什么推送成功不显示内容呢

**Comment by liangyude007** [comment]
> > 天气获取失败，具体修改方式参考上一篇Issue
> > 大佬，我fork你的，为什么推送成功不显示内容呢

你是否没有修改fork后项目的配置文件，userid等信息是否更改为自己的了？

**Comment by zZcCqQ-BBtj** [comment]
> > > 天气获取失败，具体修改方式参考上一篇Issue
> > > 大佬，我fork你的，为什么推送成功不显示内容呢
> 
> 你是否没有修改fork后项目的配置文件，userid等信息是否更改为自己的了？

不太懂，我是fork后还是按照原来的步骤填写action信息然后启用推送

**Comment by liangyude007** [comment]
> > > > 天气获取失败，具体修改方式参考上一篇Issue
> > > > 大佬，我fork你的，为什么推送成功不显示内容呢
> > 
> > 
> > 你是否没有修改fork后项目的配置文件，userid等信息是否更改为自己的了？
> 
> 不太懂，我是fork后还是按照原来的步骤填写action信息然后启用推送

1、具体的情况是，是否正确推送信息到用户手机公众号上了？如果没有那就是配置信息错误。
2、注意：现在所在的项目不是我的项目，希望你没有fork错误
3、我的项目和这个项目的不同在于：获取天气的接口，链接：
	改造后（我的项目）：url = "https://restapi.amap.com/v3/weather/weatherInfo?key=548d5a72ba6a78290dad9f64df1d5d14&city=130600"
	其中city=130600 是保定，如果你要改成其他城市只能去高德天气文档中查询城市的编码（我这里是写死的城市）
4、我目前项目对应的公众号模板：
	当前位置：{{city.DATA}} 
	今日天气：{{weather.DATA}} 
	气温：{{temperature.DATA}}℃ 
	今天是我们相见的第{{love_days.DATA}}天 
	{{words.DATA}}
5、我目前的Action配置：
	APP_ID
	APP_SECRET
	BIRTHDAY
	CITY：保定（填写城市名称）
	START_DATE
	TEMPLATE_ID
	USER_ID

希望上面的能对你有帮助

**Comment by zczczczczczczczczczczc** [comment]
老哥  是只用改获取天气的url就可以了嘛
’

**Comment by liangyude007** [comment]
> 老哥 是只用改获取天气的url就可以了嘛 ’

对 因为我也是出现了跟你一样的错误，debug后发现是天气获取失败造成的，所以改成现在的高德天气接口了，Issue中有一篇是我写的（在你提问之前写的），你可以参考一下

**Comment by zZcCqQ-BBtj** [comment]
> > > > > 天气获取失败，具体修改方式参考上一篇Issue
> > > > > 大佬，我fork你的，为什么推送成功不显示内容呢
> > > 
> > > 
> > > 你是否没有修改fork后项目的配置文件，userid等信息是否更改为自己的了？
> > 
> > 
> > 不太懂，我是fork后还是按照原来的步骤填写action信息然后启用推送
> 
> 1、具体的情况是，是否正确推送信息到用户手机公众号上了？如果没有那就是配置信息错误。 2、注意：现在所在的项目不是我的项目，希望你没有fork错误 3、我的项目和这个项目的不同在于：获取天气的接口，链接： 改造后（我的项目）：url = "https://restapi.amap.com/v3/weather/weatherInfo?key=548d5a72ba6a78290dad9f64df1d5d14&city=130600" 其中city=130600 是保定，如果你要改成其他城市只能去高德天气文档中查询城市的编码（我这里是写死的城市） 4、我目前项目对应的公众号模板： 当前位置：{{city.DATA}} 今日天气：{{weather.DATA}} 气温：{{temperature.DATA}}℃ 今天是我们相见的第{{love_days.DATA}}天 {{words.DATA}} 5、我目前的Action配置： APP_ID APP_SECRET BIRTHDAY CITY：保定（填写城市名称） START_DATE TEMPLATE_ID USER_ID
> 
> 希望上面的能对你有帮助

成功了，谢谢大佬！！！！

**Comment by liangyude007** [comment]
> > > > > > 天气获取失败，具体修改方式参考上一篇Issue
> > > > > > 大佬，我fork你的，为什么推送成功不显示内容呢
> > > > 
> > > > 
> > > > 你是否没有修改fork后项目的配置文件，userid等信息是否更改为自己的了？
> > > 
> > > 
> > > 不太懂，我是fork后还是按照原来的步骤填写action信息然后启用推送
> > 
> > 
> > 1、具体的情况是，是否正确推送信息到用户手机公众号上了？如果没有那就是配置信息错误。 2、注意：现在所在的项目不是我的项目，希望你没有fork错误 3、我的项目和这个项目的不同在于：获取天气的接口，链接： 改造后（我的项目）：url = "https://restapi.amap.com/v3/weather/weatherInfo?key=548d5a72ba6a78290dad9f64df1d5d14&city=130600" 其中city=130600 是保定，如果你要改成其他城市只能去高德天气文档中查询城市的编码（我这里是写死的城市） 4、我目前项目对应的公众号模板： 当前位置：{{city.DATA}} 今日天气：{{weather.DATA}} 气温：{{temperature.DATA}}℃ 今天是我们相见的第{{love_days.DATA}}天 {{words.DATA}} 5、我目前的Action配置： APP_ID APP_SECRET BIRTHDAY CITY：保定（填写城市名称） START_DATE TEMPLATE_ID USER_ID
> > 希望上面的能对你有帮助
> 
> 成功了，谢谢大佬！！！！

😉

**Comment by zczczczczczczczczczczc** [comment]
File "/home/runner/work/1a1a1a/1a1a1a/./main.py", line 53, in <module>
    wea, temperature = get_weather()
                       ^^^^^^^^^^^^^
  File "/home/runner/work/1a1a1a/1a1a1a/./main.py", line 25, in get_weather
    weather = res['lives'][0]
              ~~~^^^^^^^^^
KeyError: 'lives'
Error: Process completed with exit code 1.
大佬 他又报错了

**Comment by liangyude007** [comment]
> File "/home/runner/work/1a1a1a/1a1a1a/./main.py", line 53, in wea, temperature = get_weather() ^^^^^^^^^^^^^ File "/home/runner/work/1a1a1a/1a1a1a/./main.py", line 25, in get_weather weather = res['lives'][0] ~~~^^^^^^^^^ KeyError: 'lives' Error: Process completed with exit code 1. 大佬 他又报错了

错误原因：
获取天气的接口问题，目前获取天气的访问链接用的都是我自己注册的高德天气的key值，多人使用同一个key 访问量超过了高德天气的预警值，所以无法再使用。
解决方法：
1、我已经更新了自己的代码，你重新fork一下到自己名下
2、在Actions中加入一个 WEATHER_KEY 属性，填写自己注册的高德天气的key值
（目的是替换 url = "https://restapi.amap.com/v3/weather/weatherInfo?key=023510ea72b977be6e900a5c5f751053&city=410100"  这里面的key值）
3、具体如何获取高德天气key值，具体步骤参考如下：
https://blog.csdn.net/qq_51468120/article/details/127978329
