### ISSUE TITLE
请问一下啊这个问题如何解决

### ISSUE THREAD

**Issue by tianzhijiaozhiyy** [13812851221/-rxrw-daily_morning#28]
Notice:  A new release of pip is available: 22.3.1 -> 23.0.1
Notice:  To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/runner/work/rxrw-daily_morning/rxrw-daily_morning/./main.py", line 91, in <module>
    weather = get_weather()
              ^^^^^^^^^^^^^
  File "/home/runner/work/rxrw-daily_morning/rxrw-daily_morning/./main.py", line 43, in get_weather
    weather = res['data']['list'][0]
              ~~~^^^^^^^^
KeyError: 'data'
Error: Process completed with exit code 1.

**Comment by liangyude007** [comment]
换个项目试试：https://github.com/JionghaoSong/DailyMorning_Star

**Comment by hhjian666** [comment]
这个接口不让用了
